---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper-deployment-1
spec:
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
        - name: zoo1
          image: digitalwonderland/zookeeper
          ports:
          - containerPort: 2181
          env:
          - name: ZOOKEEPER_ID
            value: "1"
          - name: ZOOKEEPER_SERVER_1
            value: zoo1
          - name: ZOOKEEPER_SERVER_2
            value: zoo2
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper-deployment-2
spec:
  template:
    metadata:
      labels:
        app: zookeeper-2
    spec:
      containers:
        - name: zoo1
          image: digitalwonderland/zookeeper
          ports:
          - containerPort: 2181
          env:
          - name: ZOOKEEPER_ID
            value: "2"
          - name: ZOOKEEPER_SERVER_1
            value: zoo1
          - name: ZOOKEEPER_SERVER_2
            value: zoo2
