---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-deployment-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper-1
      version: v01
  template:
    metadata:
      labels:
        app: zookeeper-1
        version: v01
    spec:
      containers:
        - name: zoo1
          image: digitalwonderland/zookeeper
          ports:
          - containerPort: 2181
          env:
          - name: ZOOKEEPER_ID
            value: "1"
          - name: ZOOKEEPER_SERVER_1
            value: zoo1
